name: Update tvJSON from Gmail

on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install imapclient

      - name: Read Gmail and update JSON
        env:
          GMAIL_USER: ${{ secrets.lugy94766@gmail.com }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: python script.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add tvJSON.json docs/tvJSON.json

          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "Update tvJSON from Gmail"
          git push
